In [1]:
import os
import sys
import urllib.request
import json
import pandas as pd
import matplotlib.pyplot as plt
import time
import random
import requests

In [147]:
real_lucky = pd.read_csv('./real_lucky.csv')

In [165]:
pwd

'C:\\Users\\sum\\Downloads'

In [169]:
key_first = pd.read_csv('C:/Users/sum/Downloads/key_first.csv')

In [170]:
key_first.drop_duplicates()

           키워드
0          비트즙
1        비트클래식
2         비티셔츠
3         비플레인
4          비플립
...        ...
19995      통돌이
19996   통돌이세탁기
19997    통돌이오븐
19998  통돌이회전걸레
19999      통바지

[20000 rows x 1 columns]

In [148]:
real_lucky

,Unnamed: 0,연관키워드,월간검색수_PC,월간검색수_모바일,월평균클릭수_PC,월평균클릭수_모바일,월평균클릭률_PC,월평균클릭률_모바일,월평균노출광고수,경쟁정도
0,0,비플립,50,190,0.5,2.0,1.20,1.21,2,중간
1,0,빅가죽쇼퍼백,10,10,0.0,0.0,0.00,0.00,2,중간
2,0,빅골프,510,1300,9.7,63.8,2.10,5.31,13,중간
3,0,빅군모,10,10,0.0,0.0,0.00,0.00,8,중간
4,0,빅로고가디건,10,10,0.0,0.0,0.00,0.00,0,낮음
...,...,...,...,...,...,...,...,...,...,...
5296,0,톰볼리니,10,80,0.0,0.7,0.00,0.75,3,높음
5297,0,톰포드메탈선글라스,10,10,0.0,0.0,0.00,0.00,0,낮음
5298,0,톰포드스퀘어메탈선글라스,10,10,0.0,0.0,0.00,0.00,0,낮음
5299,0,톰포드스퀘어선글라스,10,10,0.0,0.0,0.00,0.00,0,낮음
5300,0,통돌이오븐,480,4300,0.7,0.3,0.17,0.01,15,높음

In [162]:
real_lucky.drop_duplicates(['연관키워드'])

,Unnamed: 0,연관키워드,월간검색수_PC,월간검색수_모바일,월평균클릭수_PC,월평균클릭수_모바일,월평균클릭률_PC,월평균클릭률_모바일,월평균노출광고수,경쟁정도
0,0,비플립,50,190,0.5,2.0,1.20,1.21,2,중간
1,0,빅가죽쇼퍼백,10,10,0.0,0.0,0.00,0.00,2,중간
2,0,빅골프,510,1300,9.7,63.8,2.10,5.31,13,중간
3,0,빅군모,10,10,0.0,0.0,0.00,0.00,8,중간
4,0,빅로고가디건,10,10,0.0,0.0,0.00,0.00,0,낮음
...,...,...,...,...,...,...,...,...,...,...
5296,0,톰볼리니,10,80,0.0,0.7,0.00,0.75,3,높음
5297,0,톰포드메탈선글라스,10,10,0.0,0.0,0.00,0.00,0,낮음
5298,0,톰포드스퀘어메탈선글라스,10,10,0.0,0.0,0.00,0.00,0,낮음
5299,0,톰포드스퀘어선글라스,10,10,0.0,0.0,0.00,0.00,0,낮음
5300,0,통돌이오븐,480,4300,0.7,0.3,0.17,0.01,15,높음

In [149]:
dirty_lucky = pd.read_csv('./key_last.csv')

In [172]:
real = pd.read_csv('./datalab.csv')

In [175]:
len(real)

31149

In [173]:
real.drop_duplicates()

,Unnamed: 0,Unnamed: 0_x,날짜,ratio,키워드_x,Unnamed: 0.1,Unnamed: 0_y,연관키워드,월간검색수_PC,월간검색수_모바일,월평균클릭수_PC,월평균클릭수_모바일,월평균클릭률_PC,월평균클릭률_모바일,월평균노출광고수,경쟁정도,키워드_y,category1Name
0,0,0,2022-01-01,100.00000,비플립,0,0,비플립,50,190,0.5,2.0,1.20,1.21,2,중간,비플립,화장품/미용
1,1,1,2022-02-01,74.02985,비플립,0,0,비플립,50,190,0.5,2.0,1.20,1.21,2,중간,비플립,화장품/미용
2,2,2,2022-03-01,74.02985,비플립,0,0,비플립,50,190,0.5,2.0,1.20,1.21,2,중간,비플립,화장품/미용
3,3,3,2022-04-01,74.47761,비플립,0,0,비플립,50,190,0.5,2.0,1.20,1.21,2,중간,비플립,화장품/미용
4,4,4,2022-05-01,72.23880,비플립,0,0,비플립,50,190,0.5,2.0,1.20,1.21,2,중간,비플립,화장품/미용
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31144,31144,1918,2022-08-01,75.74123,통돌이오븐,5338,0,통돌이오븐,480,4300,0.7,0.3,0.17,0.01,15,높음,통돌이오븐,디지털/가전
31145,31145,1919,2022-09-01,62.40684,통돌이오븐,5338,0,통돌이오븐,480,4300,0.7,0.3,0.17,0.01,15,높음,통돌이오븐,디지털/가전
31146,31146,1920,2022-10-01,71.82495,통돌이오븐,5338,0,통돌이오븐,480,4300,0.7,0.3,0.17,0.01,15,높음,통돌이오븐,디지털/가전
31147,31147,1921,2022-11-01,52.29110,통돌이오븐,5338,0,통돌이오븐,480,4300,0.7,0.3,0.17,0.01,15,높음,통돌이오븐,디지털/가전
31148,31148,1922,2022-12-01,49.88108,통돌이오븐,5338,0,통돌이오븐,480,4300,0.7,0.3,0.17,0.01,15,높음,통돌이오븐,디지털/가전

In [159]:
dirty_lucky['키워드'] = dirty_lucky['키워드'].str.replace(' ', '')

In [171]:
dirty_lucky.drop_duplicates()

           키워드 category1Name
0          비트즙            식품
1        비트클래식            식품
2         비티셔츠          패션의류
3         비플레인        화장품/미용
4          비플립        화장품/미용
...        ...           ...
19995      통돌이        디지털/가전
19996   통돌이세탁기        디지털/가전
19997    통돌이오븐        디지털/가전
19998  통돌이회전걸레         생활/건강
19999      통바지          패션의류

[19911 rows x 2 columns]

In [160]:
total = pd.merge(real_lucky, dirty_lucky , left_on = '연관키워드',right_on = '키워드', how = 'left')

In [161]:
total

,Unnamed: 0,연관키워드,월간검색수_PC,월간검색수_모바일,월평균클릭수_PC,월평균클릭수_모바일,월평균클릭률_PC,월평균클릭률_모바일,월평균노출광고수,경쟁정도,키워드,category1Name
0,0,비플립,50,190,0.5,2.0,1.20,1.21,2,중간,비플립,화장품/미용
1,0,빅가죽쇼퍼백,10,10,0.0,0.0,0.00,0.00,2,중간,빅가죽쇼퍼백,패션잡화
2,0,빅골프,510,1300,9.7,63.8,2.10,5.31,13,중간,빅골프,스포츠/레저
3,0,빅군모,10,10,0.0,0.0,0.00,0.00,8,중간,빅군모,패션잡화
4,0,빅로고가디건,10,10,0.0,0.0,0.00,0.00,0,낮음,빅로고가디건,패션의류
...,...,...,...,...,...,...,...,...,...,...,...,...
5334,0,톰볼리니,10,80,0.0,0.7,0.00,0.75,3,높음,톰볼리니,패션의류
5335,0,톰포드메탈선글라스,10,10,0.0,0.0,0.00,0.00,0,낮음,톰포드메탈선글라스,패션잡화
5336,0,톰포드스퀘어메탈선글라스,10,10,0.0,0.0,0.00,0.00,0,낮음,톰포드스퀘어메탈선글라스,패션잡화
5337,0,톰포드스퀘어선글라스,10,10,0.0,0.0,0.00,0.00,0,낮음,톰포드스퀘어선글라스,패션잡화
5338,0,통돌이오븐,480,4300,0.7,0.3,0.17,0.01,15,높음,통돌이오븐,디지털/가전

In [155]:
total.drop_duplicates(['연관키워드'])

,Unnamed: 0,연관키워드,월간검색수_PC,월간검색수_모바일,월평균클릭수_PC,월평균클릭수_모바일,월평균클릭률_PC,월평균클릭률_모바일,월평균노출광고수,경쟁정도,키워드,category1Name
0,0,비플립,50,190,0.5,2.0,1.20,1.21,2,중간,비플립,화장품/미용
1,0,빅가죽쇼퍼백,10,10,0.0,0.0,0.00,0.00,2,중간,빅가죽쇼퍼백,패션잡화
2,0,빅골프,510,1300,9.7,63.8,2.10,5.31,13,중간,빅골프,스포츠/레저
3,0,빅군모,10,10,0.0,0.0,0.00,0.00,8,중간,빅군모,패션잡화
4,0,빅로고가디건,10,10,0.0,0.0,0.00,0.00,0,낮음,빅로고가디건,패션의류
...,...,...,...,...,...,...,...,...,...,...,...,...
5296,0,톰볼리니,10,80,0.0,0.7,0.00,0.75,3,높음,톰볼리니,패션의류
5297,0,톰포드메탈선글라스,10,10,0.0,0.0,0.00,0.00,0,낮음,NaN,NaN
5298,0,톰포드스퀘어메탈선글라스,10,10,0.0,0.0,0.00,0.00,0,낮음,NaN,NaN
5299,0,톰포드스퀘어선글라스,10,10,0.0,0.0,0.00,0.00,0,낮음,NaN,NaN
5300,0,통돌이오븐,480,4300,0.7,0.3,0.17,0.01,15,높음,통돌이오븐,디지털/가전

In [143]:
total.to_csv("reallucky.csv")

In [110]:
plus = pd.read_csv('./cell.csv')

In [25]:
lab = pd.read_csv('./lab_all.csv') # 30570

In [112]:
plus_1 = pd.merge(lab, plus , left_on = '키워드',right_on = '연관키워드', how = 'left')

In [115]:
plus_1.to_csv('datalab.csv')

In [30]:
lab.join(total)

ValueError: columns overlap but no suffix specified: Index(['Unnamed: 0'], dtype='object')